/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mahasiswa;

import java.sql.*;
import javax.swing.JOptionPane;
import utama.koneksi_to_db;
import utama.konstanta;

public class ubah_password extends javax.swing.JFrame {

    private String uid = konstanta.UID;
    
    public ubah_password() {
        initComponents();
        
        koneksi_to_db.setupDatabaseConnection();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        batal_btn = new javax.swing.JButton();
        simpan_btn = new javax.swing.JButton();
        statusPass_lbl = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        konfrPass_pf = new javax.swing.JPasswordField();
        passLama_pf = new javax.swing.JPasswordField();
        passBaru_pf = new javax.swing.JPasswordField();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Logo Jurusanl.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 67, 80));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ubah Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 80));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Konfirmasi Password Baru");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Password Lama");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Password Baru");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        batal_btn.setBackground(new java.awt.Color(255, 255, 204));
        batal_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        batal_btn.setText("Batal");
        batal_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batal_btnActionPerformed(evt);
            }
        });
        jPanel2.add(batal_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));

        simpan_btn.setBackground(new java.awt.Color(255, 255, 204));
        simpan_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        simpan_btn.setText("Simpan");
        simpan_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpan_btnActionPerformed(evt);
            }
        });
        jPanel2.add(simpan_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        statusPass_lbl.setText("jLabel7");
        jPanel2.add(statusPass_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 126, -1, 30));

        jLabel7.setText(".");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 156, 60, 70));

        konfrPass_pf.setBackground(new java.awt.Color(255, 255, 204));
        konfrPass_pf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        konfrPass_pf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                konfrPass_pfKeyReleased(evt);
            }
        });
        jPanel2.add(konfrPass_pf, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 170, -1));

        passLama_pf.setBackground(new java.awt.Color(255, 255, 204));
        passLama_pf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(passLama_pf, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 170, -1));

        passBaru_pf.setBackground(new java.awt.Color(255, 255, 204));
        passBaru_pf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(passBaru_pf, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 170, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 400, 220));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void simpan_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpan_btnActionPerformed
        String pass_lama = new String(passLama_pf.getPassword());
        String pass_baru = new String(passBaru_pf.getPassword());
        String konfr_pass = new String(konfrPass_pf.getPassword());
        
        Connection connection = koneksi_to_db.getConnection();
        if (connection != null){
            String get_oldPass = "SELECT password FROM info_login_mhs WHERE uid = ?";
            try(PreparedStatement state = connection.prepareStatement(get_oldPass)){
                state.setString(1, uid);
                ResultSet rs = state.executeQuery();
                if (rs.next()){
                    String password = rs.getString("password");
                    if (pass_lama.equals(password)){
                        if (konfr_pass.equals(pass_baru)){
                            if(connection != null) {
                                String ubah_pass = "UPDATE info_login_mhs SET password = ? WHERE uid = ?";
                                try (PreparedStatement statee = connection.prepareStatement(ubah_pass)){
                                    statee.setString(1, konfr_pass);
                                    statee.setString(2, uid);
                                    statee.executeUpdate();
                                    JOptionPane.showMessageDialog(this, "Password Berhasil diubah!");
                                    new mahasiswa.profil_mhs().setVisible(true);
                                    this.dispose();
                                } catch (Exception e) {
                                    System.out.println("Query Error");
                                }
                            }
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Password Lama Salah!");
                    }
                }
            } catch (SQLException e){
                System.out.println("Query Error");
            }
        }
    }//GEN-LAST:event_simpan_btnActionPerformed

    private void batal_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batal_btnActionPerformed
        new mahasiswa.profil_mhs().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_batal_btnActionPerformed

    private void konfrPass_pfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_konfrPass_pfKeyReleased
        updateLabel();
    }//GEN-LAST:event_konfrPass_pfKeyReleased

    private void updateLabel(){
        String pass_baru = new String(passBaru_pf.getPassword());
        String konfr_pass = new String(konfrPass_pf.getPassword());
        
        if (pass_baru.equals(konfr_pass)) {
            statusPass_lbl.setText("✅");
            statusPass_lbl.setForeground(java.awt.Color.GREEN);
        } else{
            statusPass_lbl.setText("Password Berbeda");
            statusPass_lbl.setForeground(java.awt.Color.RED);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ubah_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ubah_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ubah_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ubah_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ubah_password().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batal_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField konfrPass_pf;
    private javax.swing.JPasswordField passBaru_pf;
    private javax.swing.JPasswordField passLama_pf;
    private javax.swing.JButton simpan_btn;
    private javax.swing.JLabel statusPass_lbl;
    // End of variables declaration//GEN-END:variables
}
